apiVersion: batch/v1
kind: CronJob
metadata:
  name: grpcgoonch-headless-long-client-pickfirst-cronjob
  labels:
    app: grpcgoonch-headless-long-client-pickfirst
spec:
  schedule: "0/8 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: grpcgoonch-headless-long-client-pickfirst
    spec:
      template:
        spec:
          containers:
          - name: grpcgoonch-headless-long-client-pickfirst
            image: thaigoonch/grpcgoonch-headless-long-client-pickfirst:1.0
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
          nodeSelector:
            goonchrole: "nonserver"